name: reptile encounters
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Berkshire reptile encounters
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffea35'
    - '#42563a'
    - '#a4822c'
    - '#c8a541'
    - '#817757'
  brandStrength: 1
  lightness: 0.0625
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
