name: reptile encounters
favicon: null
layout_spectrum: 1
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e3219'
    - '#070604'
    - '#596851'
    - '#b8a797'
    - '#edee1a'
  brandStrength: 1
  lightness: 0.8474874147213995
  saturation: 1
  rhythmicContrast: 0.5245832446962595
purpose: []
